FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    scapy \
    net-tools \
    iputils-ping \
    dnsutils \
    tcpdump \
    vim \
    nano \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install scapy

WORKDIR /attack

CMD ["/bin/bash"]
