FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    dnsutils \
    net-tools \
    iputils-ping \
    curl \
    wget \
    vim \
    nano \
    && rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]
